print('_________________________________________________')
print('____________ Welcome to the Discover ____________')
print('_________________________________________________')
x = input('write something to discover the types of it:')
print('_________________________________________________')
print('the primitive type of', x, 'is ', type(x))
print(x, ' is equal to: ')
print('Alphanumeric:   |', x.isalnum())
print('Alphabet:       |', x.isalpha())
print('Digit:          |', x.isdigit())
print('ASCII:          |', x.isascii())
print('Lower letter:   |', x.islower())
print('Decimal number: |', x.isdecimal())
print('Identifier:     |', x.isidentifier())
print('Number:         |', x.isnumeric())
print('Printable:      |', x.isprintable())
print('Space:          |', x.isspace())
print('Title:          |', x.istitle())
print('Upper:          |', x.isupper())
