print('Convertor')
x = float(input('Tel me one measure in meters: '))
Km = x / (10**1)
Hm = x / (10**2)
Cam = x / (10**3)
Dec = x * (10**1)
Cen = x * (10**2)
Mi = x * (10**3)
print('The conversions of {} is: \n{} Millimeters \n{} Centimeters \n{} Decimeters\n{} Meters \n{} Decameters \n{} Hectometers \n{} Kilometers '.format(x, Mi, Dec, Cen, x, Cam, Hm, Km))