print('Bem vindo ao analisador de nomes')
print('--------------------------------')
Nom = input('Qual seu nome? ')
print('________________________________')
print('Seu nome em maiusculo ficaria {}'.format(Nom.upper()))
print('Seu nome em minusculo ficaria {}'.format(Nom.lower()))
Nomd = Nom.split()
print('Seu primeiro nome tem {} letras'.format(len(Nomd[0])))
print('E seu nome tem ao todo {} letras'.format(len("".join(Nomd))))
